%clear all
close all

%% Load previously computed RSA results
load('RSA_RESULTS.mat')

%% Clear, intuitive layer names
layerNames = { ...
    'Input', ...
    'Convolution 1', ...
    'Batch Norm', ...
    'ReLU', ...
    'Pooling', ...
    'Convolution 2', ...
    'Batch Norm', ...
    'ReLU', ...
    'Convolution 3', ...
    'Batch Norm', ...
    'Residual Addition', ...
    'ReLU', ...
    'Fully Connected 1', ...
    'Global Average Pooling', ...
    'Fully Connected 2'};

x = 1:15;

%% Plot selected RSA measures
figure('Color','w','Position',[100 100 1500 650])
hold on

% Reflectance
plot(x, CORS(1:15,2), '-', ...
    'LineWidth',4, ...
    'DisplayName','Reflectance');

% Mean disk intensity
plot(x, CORS(1:15,3), '-', ...
    'LineWidth',4, ...
    'DisplayName','Mean disk intensity');

% Difference between disk and background
plot(x, CORS(1:15,7), '-', ...
    'LineWidth',4, ...
    'DisplayName','Disk - background');

% Michelson contrast
plot(x, CORS(1:15,8), '-', ...
    'LineWidth',4, ...
    'DisplayName','Michelson contrast');

% Ratio
plot(x, CORS(1:15,9), '-', ...
    'LineWidth',4, ...
    'DisplayName','Disk / background ');


%% Figure formatting
set(gca, ...
    'LineWidth',2.5, ...
    'FontSize',17, ...
    'XTick',x, ...
    'XTickLabel',layerNames, ...
    'XTickLabelRotation',45, ...
    'TickDir','out');

ylabel('RSA correlation','FontSize',21)

legend('Location','best', 'FontSize',16)
legend boxoff

xlim([1 15])
box off

set(gca,'FontName','Arial')